#
MYSRCPATH=${BASH_SOURCE%/*}
if [[ "X${MYSRCPATH#.}" != "X${MYSRCPATH}" ]];then
	MYSRCPATH=${PWD}/${MYSRCPATH#.}
fi
PYTHONPATH=${MYSRCPATH}:$PYTHONPATH
export PYTHONPATH

PATH=${MYSRCPATH}/bin:$PATH
export PATH
